FROM nginx

# Copy files
COPY index.html /usr/share/nginx/html/

# Export http port
EXPOSE 80

#Command for creating an image
#docker build -t my-nginx .
# Command for running a container
#docker run -d -p 80:80 --name webserver my-nginx